version: '3.8'
services:
  backend:
    working_dir: /app
    volumes:
      - ./backend:/app
    image: python:3.11-slim
    command: sh -c "pip install fastapi uvicorn requests && uvicorn main:app --host 0.0.0.0 --port 8002 --reload"
    ports:
      - "8002:8002"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8082:80"
